apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: { { include "lazy-lecture.fullname" . } }-api-mock-pvc
  labels:
    {{- include "lazy-lecture.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: { { .Values.api.volumes.mock.size | default "1Gi" } }
