# templates/secret-rabbitmq.yaml
{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lazy-lecture.fullname" . }}-rabbitmq-secret
  labels:
    {{- include "lazy-lecture.labels" . | nindent 4 }}
type: Opaque
data:
  RMQ_USER: {{ .Values.rabbitmq.env.RMQ_USER | default "user" | b64enc | quote }}
  RMQ_PASS: {{ .Values.rabbitmq.env.RMQ_PASS | default "pass" | b64enc | quote }}
{{- end }}
