# templates/secret-postgres.yaml
  { { - if .Values.postgres.enabled } }
apiVersion: v1
kind: Secret
metadata:
  name: { { include "lazy-lecture.fullname" . } }-postgres-secret
  labels:
    {{- include "lazy-lecture.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DB: { { .Values.postgres.env.POSTGRES_DB | default "ChaikaGoods" | b64enc | quote } }
  POSTGRES_USER: { { .Values.postgres.env.POSTGRES_USER | default "postgres" | b64enc | quote } }
  POSTGRES_PASSWORD: { { .Values.postgres.env.POSTGRES_PASSWORD | default "default-password" | b64enc | quote } }
  { { - end } }
