services:
  bot:
    build: bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}

  worker:
    build: worker
    volumes:
      - worker_cache:/cache:rw
      - ./volumes/object_storage:/object_storage:rw

    environment:
      - DEVICE=${DEVICE:-cpu}
      - WHISPER_MODEL_NAME=${WHISPER_MODEL_NAME:-base}
      - DOWNLOAD_ROOT=${DOWNLOAD_ROOT:-/cache}
      - PIKA_HOST=rabbitmq
      - PIKA_PORT=5672
      - PIKA_USER=${RMQ_USER:-user}
      - PIKA_PASS=${RMQ_PASS:-pass}
      - PIKA_QUEUE=task_queue
      - OBJECT_STORAGE_PATH=${OBJECT_STORAGE_PATH:-/object_storage}
      - SECRET_WORKER_TOKEN=${SECRET_WORKER_TOKEN}
      - API_BASE_URL=http://api:8000
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:4.0.3-management
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    environment:
      - RMQ_USER=${RMQ_USER:-user}
      - RMQ_PASS=${RMQ_PASS:-pass}
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2Gb
        reservations:
          cpus: '0.5'
          memory: 1Gb

  web-ui:
    build: web-ui
    expose:
      - 9000
    ports:
      - 9000:80
    environment:
      - NODE_ENV=production

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: ./config/dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./api/config/.env
    environment:
      - SECRET_WORKER_TOKEN=${SECRET_WORKER_TOKEN}
    volumes:
      - ./api/source:/app/source
      - ./api/mock:/app/mock
      - ./volumes/object_storage:/app/object_storage:rw
    depends_on:
      - rabbitmq
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./api/config/.env
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  pgadmin:
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-kek@ll.ru}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-asdfghjk!@#$%^&*}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE:-False}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

volumes:
  worker_cache:
  rabbitmq:
  pgadmin-data:
  pg-data:
