# templates/pvc-postgres.yaml
{{- if .Values.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lazy-lecture.fullname" . }}-postgres-pvc
  labels:
    {{- include "lazy-lecture.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.postgres.persistence.size }}"
{{- end }}
