apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    isDefault: true
    editable: true
    url: postgres:5432
    database: database
    user: user
    secureJsonData:
      password: password
    jsonData:
      postgresVersion: 1200
      sslmode: disable
