{
 "title": "statistic",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "time_range",
    "query": "24 hours,7 days,1 month,all time"
   }
  ]
 },
 "panels": [
  {
   "title": "Количество транскрипций за...",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  COUNT(*) AS total_chunks\r\nFROM \r\n  \"TranscriptionChunk\"\r\nWHERE \r\n  CASE\r\n    WHEN '${time_range}' = '24 hours' THEN create_date >= NOW() - INTERVAL '24 hours'\r\n    WHEN '${time_range}' = '7 days' THEN create_date >= NOW() - INTERVAL '7 days'\r\n    WHEN '${time_range}' = '1 month' THEN create_date >= NOW() - INTERVAL '1 month'\r\n    ELSE TRUE -- для \"all time\"\r\n  END;\r\n"
    }
   ]
  },
  {
   "title": "Длина обработанного аудио за....",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  COALESCE(SUM(T.chunk_size_secs * chunk_count), 0) AS total_audio_length\r\nFROM \r\n  \"Transcription\" T\r\nJOIN (\r\n  SELECT \r\n    transcript_id, \r\n    COUNT(*) AS chunk_count,\r\n    MAX(update_date) AS last_update_date\r\n  FROM \r\n    \"TranscriptionChunk\"\r\n  GROUP BY \r\n    transcript_id\r\n) TC\r\nON \r\n  T.id = TC.transcript_id\r\nWHERE \r\n  CASE\r\n    WHEN '${time_range}' = '24 hours' THEN TC.last_update_date >= NOW() - INTERVAL '24 hours'\r\n    WHEN '${time_range}' = '7 days' THEN TC.last_update_date >= NOW() - INTERVAL '7 days'\r\n    WHEN '${time_range}' = '1 month' THEN TC.last_update_date >= NOW() - INTERVAL '1 month'\r\n    ELSE TRUE -- для \"all time\"\r\n  END;\r\n"
    }
   ]
  },
  {
   "title": "Количество новых пользователей за последний месяц",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS new_users_last_month\r\nFROM \"User\"\r\nWHERE create_date >= NOW() - INTERVAL '1 month';"
    }
   ]
  },
  {
   "title": "Общее количество пользователей",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_users\r\nFROM \"User\";\r\n"
    }
   ]
  }
 ]
}