FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y ffmpeg && rm -rf /var/lib/apt/lists/*

COPY config/requirements.txt config/
RUN pip install --no-cache-dir -r config/requirements.txt

COPY alembic.ini .
COPY source source

CMD alembic upgrade head && uvicorn source.main:app --host 0.0.0.0 --reload
