name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python dependencies for bot
        run: |
          cd bot
          pip install -r requirements.txt

      - name: Install Python dependencies for worker
        run: |
          cd worker
          pip install -r requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install NPM dependencies for web-ui
        run: |
          cd web-ui
          npm install

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ESLint for web-ui
        run: |
          cd web-ui
          npm run lint

      - name: Run Python Linter for bot
        run: |
          cd bot
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Python Linter for worker
        run: |
          cd worker
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Unit and Integration Tests for worker
        run: |
          cd worker
          chmod +x run_tests.sh
          ./run_tests.sh

  ml-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ML Tests for worker
        run: |
          cd worker
          chmod +x run_ml_tests.sh
          ./run_ml_tests.sh
