name: Deploy to Kubernetes

on:
  workflow_run:
      workflows:
        - CI Pipeline  # Имя пайплайна CI
      types:
        - completed
  push:
    branches:
      - main
      - feature/ci_cd_integration

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Логин в Docker реестр
      - name: Log in to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Сборка и пуш Docker-образа
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:latest
            ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}

      # 4. Установка kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # 5. Настройка Kubeconfig
      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      # 6. Применение манифестов Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/<DEPLOYMENT_NAME> <CONTAINER_NAME>=${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          kubectl rollout status deployment/<DEPLOYMENT_NAME>
